language: node_js

node_js:
  - "stable"

jobs:
  include:
    - stage: test
      script: npm t
    - stage: npm release
      if: tag IS present
      if: branch = master
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
          branch: master
